version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      'MINOR_AND_PATCH':
        update-types:
          - 'minor'
          - 'patch'
    open-pull-requests-limit: 5
  - package-ecosystem: 'github-actions'
    directory: '/.github/workflows'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
