name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Lint and Test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Extract Node.js and pnpm versions
        id: versions
        run: |
          echo "node-version=$(jq -r '.engines.node' package.json)" >> $GITHUB_OUTPUT
          echo "pnpm-version=$(jq -r '.engines.pnpm' package.json)" >> $GITHUB_OUTPUT

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ steps.versions.outputs.pnpm-version }}

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ steps.versions.outputs.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linting
        run: pnpm check

      - name: Run tests
        run: pnpm test
