name: Test

on:
  pull_request:

jobs:
  frontend-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set pnpm version
        shell: bash
        run: |
          pnpm_version=$(jq -r '.engines.pnpm' package.json)
          echo "PNPM_VERSION=${pnpm_version}" >> "$GITHUB_ENV"
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i --frozen-lockfile --prefer-offline --strict-peer-dependencies --ignore-scripts
      - name: Lint
        run: pnpm check
